### ISSUE TITLE
Remove `depends` fields from `conda` info?

### ISSUE THREAD

**Issue by jaimergp** [napari/npe2api#3]
Right now the conda metadata is fetched from Anaconda.org's metadata, which is extracted from the tarballs originally uploaded. However, during CDN sync, maintainers are given an opportunity to patch the generated `repodata.json` file (which also comes from aggregating the metadata in tarballs), in case and adjustment in dependencies was needed.

Since there's a risk the `depends` information returned from the API is out-of-date for practical purposes (the solver doesn't use the API at all, but the potentially patched `repodata.json` instead), I'd suggest we remove those fields from the published metadata. If anybody needs that information, they won't be tempted to use it and will be forced to do the correct thing: query the `repodata.json` files with `conda search`, `mamba repoquery` or similar.

What do you think @tlambert03 ? I'd be happy to submit the PR, but I thought I should explain why first :)

**Comment by jaimergp** [comment]
On second thought, we might want to use the `depends` metadata to anticipate if the user's `napari` is compatible with the plugin or not. So an alternative would be to fill-in those `depends` fields from the fetched `repodata.json`. This will make the generation a bit slower, but not too much, I'd say.

**Comment by tlambert03** [comment]
I'm happy with either approach!  Fine just to strip it if it's potentially misleading (that could be done [right here where we also get rid of ndownloads](https://github.com/napari/npe2api/blob/0657b3439adedba4ff33a5635ec793cc5a681462/scripts/reindex.py#L115))

or ... if you want to show me how to fetch and parse `repodata.json` instead/additionally, that's also great.

At the moment, I'm mostly just gathering this data here under the assumption that it might be useful to you at some point, so feel free to turn it into whatever you think you would be most useful.  It'd be nice if we could keep it all _relatively_ quick (currently the whole fetch process takes about 2 mins), but better to be useful than fast :)

**Comment by jaimergp** [comment]
Is it fine to depend on `conda` or do you want to keep it stdlib-only?

**Comment by tlambert03** [comment]
like in `reindex.py` and `fetch.yaml`?  fine with me.  i don't imagine those will ever be used outside of this repo, and if we need to extract the dependency later that's fine too
