### ISSUE TITLE
Feature Proposal : API documentation

### ISSUE THREAD

**Issue by rogueloop** [napari/npe2api#34]
Hi there! I'd love to help set up API documentation for your project. I've been working with a documentation platform called LiveAPI, and I can get everything set up for you at no cost.

All we ask in return is some feedback or a brief testimonial.
Feel free to check out the product here: [LiveAPI](https://hexmos.com/liveapi).

Looking forward to hearing from you!

**Comment by DragaDoncila** [comment]
Thanks for opening this issue. Currently `npe2api` is purely maintained for internal usage and we don't need API docs. I'll be closing this now.
